### ISSUE TITLE
Multiple issues with the latest vscode

### ISSUE THREAD

**Issue by dodalovic** [bradlc/vscode-tailwindcss#100] opened 2020-03-16 20:55 UTC
Hi, thanks for providing the extension, first of all!

I'd like to report some issues I'm currently facing:

* `@apply` doesn't help with autocomplete
![image](https://user-images.githubusercontent.com/6358061/76798738-701c9000-67d0-11ea-8b15-b5aa680da232.png)
* peeking on hover doesn't do anything
* when applying class, such as `w-3/5`, I can't navigate to it (maybe since it's `w-3\/5` in the generated css file)

Thanks in advance

**Comment by bradlc** [comment] 2020-03-18 23:14
Hey @dodalovic. To clarify, is the extension working _at all_ for you?

**Comment by dodalovic** [comment] 2020-03-19 11:48
Hey, I’m just able to get autocompletes, but couldn’t peek etc

**Comment by chrislentz** [comment] 2020-03-22 00:07
The extensions isn't working at all for me.

**Comment by heybourn** [comment] 2020-03-22 00:42
It seems like the extension has stopped working for me also. I've restarted VS, my PC and reinstalled.

**Comment by junaidatique** [comment] 2020-03-22 09:37
It is not working for me at all.

**Comment by rbaffy** [comment] 2020-03-24 01:36
Not working for me at all either since VSC 1.43.1

**Comment by quartzeast** [comment] 2020-03-24 09:33
Not working for me at all also

**Comment by bethmduggan** [comment] 2020-03-25 09:27
Not working for me either

**Comment by ndan** [comment] 2020-03-26 09:43
You should create `tailwind.config.js` at the root of your project.

**Comment by chrislentz** [comment] 2020-03-26 14:04
> You should create `tailwind.config.js` at the root of your project to make it work.
> 
> See https://github.com/bradlc/vscode-tailwindcss/blob/master/package.json#L26

That works, but that is a bad architectural decision for a plugin. Many projects contain subfolders which hold the build specific aspects of the project. For instance, in my open source project (https://github.com/chrislentz/tailwindcss-docker-playground), the build specific code lives inside a `/src` subfolder. The root is reserved for Docker configuration, readme, and gitignore.

It would be beneficial for this plugin to support looking for the config in various locations instead of requiring all projects adhere to a single structure to work.

**Comment by tomhermans** [comment] 2020-04-01 17:56
installing new mbp here, doesn't seem to work with VSCode Version: 1.43.2

**Comment by giacomorebonato** [comment] 2020-04-05 16:28
I have `tailwind.config.js` but I don't get any autocompletion.
It used to work until some days ago.

**Comment by Disane87** [comment] 2020-04-05 21:20
It's broken now.

**Comment by bethmduggan** [comment] 2020-04-05 22:58
Here is what worked for me.  Move tailwind.config.js to the the root of the project and restart vscode.
When the drop down does not automatically show inside the class=""... I can hit Ctrl-Space and it will display.  I am using windows machine.  Sometimes it will work as designed and sometimes I have to choose the Ctrl-Space.

**Comment by giacomorebonato** [comment] 2020-04-06 08:25
I take something back.
On a fresh configured create-react-app it's working:
https://github.com/giacomorebonato/react-tailwind

It's not working on this other one:
https://github.com/giacomorebonato/insta-mino/tree/master/packages/client/src

Not that the root of the front-end project, that I am opening with VSCode is not the root of the repo, but I don't understand why it matters.

**Comment by AHBruns** [comment] 2020-04-07 07:52
> I take something back.
> On a fresh configured create-react-app it's working:
> https://github.com/giacomorebonato/react-tailwind
> 
> It's not working on this other one:
> https://github.com/giacomorebonato/insta-mino/tree/master/packages/client/src
> 
> Note that the root of the front-end project, that I am opening with VSCode is not the root of the repo, but I don't understand why it should matters.

I just cloned the first repo and tried editing the a className and got nothing. It's working for you?

**Comment by AHBruns** [comment] 2020-04-07 07:58
> > I take something back.
> > On a fresh configured create-react-app it's working:
> > https://github.com/giacomorebonato/react-tailwind
> > It's not working on this other one:
> > https://github.com/giacomorebonato/insta-mino/tree/master/packages/client/src
> > Note that the root of the front-end project, that I am opening with VSCode is not the root of the repo, but I don't understand why it should matters.
> 
> I just cloned the first repo and tried editing a className and got nothing. It's working for you?

Weird, tried it again a few minutes later and it worked fine. Seems like something is taking ages to index.

**Comment by pavelloz** [comment] 2020-04-08 14:47
Couldnt bring it back to life, [found this](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion), which is good enough while waiting for a fix.

**Comment by dixonge** [comment] 2020-04-20 14:59
Well, at least @bradlc replied to an issue so we know he's still alive. But no fixes since then.

h/t to @pavelloz for the link to the optional Intellisense!

**Comment by deadcoder0904** [comment] 2020-04-25 09:01
Doesn't work for me in a React app with Next.js

**Comment by bradlc** [comment] 2020-04-28 23:33
Hey everyone. Sorry for the radio silence on this one. Just want to clear a couple of things up that should totally be in the readme:

* You do need a Tailwind CSS config file (`{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js`) for the extension to activate, but this does **not** need to be in the root of your workspace
* The `tailwindcss` package should exist at `node_modules/tailwindcss` in your workspace

If both of these requirements are met, and **you have reloaded your VS Code window** (`Command Palette > "Developer: Reload Window"`) then there is some other issue going on.

Having said that I'd like to encourage people to try out [`v0.3.0-alpha.1`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.1) and see if you have any success with that version as it's quite different to the current release so might solve your issues.

**Comment by dixonge** [comment] 2020-04-30 11:23
@bethmduggan Nice! Ctrl+space works on Mac as well. Very helpful.

@bradlc I installed the v3 alpha and so far everything seems to be working as expected. Thank you!

**Comment by deadcoder0904** [comment] 2020-04-30 11:40
@bradlc Is there a reason it needs a Tailwind CSS config?

**Comment by sevenseacat** [comment] 2020-05-03 15:55
it seems to work.... kinda intermittently here. (Testing with 0.3.0-alpha1). In my .html.leex file which I've told VSCode to treat as HTML (EEx) it doesn't work at all, but when I treat it as a HTML file it works. It also only works if my node_modules folder is at the root of my workspace (which in my app it isn't).

**Comment by bradlc** [comment] 2020-05-03 20:43
@sevenseacat `HTML (EEx)` was not supported until just now, in [`v0.3.0-alpha.2`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0-alpha.2)

This version also has a slight tweak to how modules are resolved within your workspace so might fix your `node_modules` issue.

> Is there a reason it needs a Tailwind CSS config?

@deadcoder0904 Yes and no. The extension _could_ provide completions etc. based off the default Tailwind config. I just need to have a think about the best way to do this.

**Comment by sevenseacat** [comment] 2020-05-04 01:02
I'll test it out, thanks! I saw that the filetype was in the list of HTML_LANGUAGES in previous versions so thought it would work? I dunno. Will try it out shortly and let you know, thanks so much

**Comment by bradlc** [comment] 2020-06-11 16:19
Going to close this now that [`v0.3.0`](https://github.com/bradlc/vscode-tailwindcss/releases/tag/v0.3.0) is released. If you encounter any more problems please open a new issue

**Closed by bradlc** 2020-06-11 16:19 UTC

**Comment by IgorArnaut** [comment] 2025-04-18 09:47
> Hi, thanks for providing the extension, first of all!
> 
> I'd like to report some issues I'm currently facing:
> 
>     * `@apply` doesn't help with autocomplete
>       ![image](https://user-images.githubusercontent.com/6358061/76798738-701c9000-67d0-11ea-8b15-b5aa680da232.png)
> 
>     * peeking on hover doesn't do anything
> 
>     * when applying class, such as `w-3/5`, I can't navigate to it (maybe since it's `w-3\/5` in the generated css file)
> 
> 
> Thanks in advance
Set the CSS file language mode to Tailwind CSS.
