### ISSUE TITLE
Why not support "important" field in tailwind.config.js?

### ISSUE THREAD

**Issue by masihjahangiri** [bradlc/vscode-tailwindcss#103] opened 2020-04-07 07:29 UTC
When I add `important: '#root'` to my config caused vscode-tailwind plugin to fails.

**Comment by bradlc** [comment] 2020-04-22 17:42
Hey @masihjahangiri – I'm going to close this as a duplicate of #96. You can follow along there for updates

**Closed by bradlc** 2020-04-22 17:42 UTC
